export const TRIP = {
  meta: {
    title: "Kanada 2026",
    travelers: ["Robert", "Edith", "Pia"],
    departureISO: "2026-08-01T09:00:00+02:00",
    returnISO:    "2026-08-18T08:20:00+02:00",
    totalDays: 18,
  },

  flights: [
    {
      id: "hinflug",
      label: "Hinflug",
      flightNumbers: ["OS 55"],
      date: "2026-08-01",
      from: { city: "Wien", airport: "VIE", terminal: "Terminal 3", time: "11:00" },
      to:   { city: "Montréal", airport: "YUL", time: "13:50" },
      duration: "8h 50min",
      aircraft: "Boeing 767-300",
      class: "Premium Economy",
      confirmation: "9RB932",
      document: "docs/flug-wien-montreal.pdf",
    },
    {
      id: "rueckflug",
      label: "Rückflug",
      flightNumbers: ["LH 6557", "LH 6523"],
      date: "2026-08-17",
      from: { city: "Halifax", airport: "YHZ", time: "14:05" },
      to:   { city: "Wien", airport: "VIE", time: "08:20 (+1)" },
      stopover: { city: "Toronto", airport: "YYZ", terminal: "Terminal 1" },
      duration: "13h 15min",
      confirmation: "9RB932",
      document: "docs/flug-wien-montreal.pdf",
    },
  ],

  carRental: {
    company: "Alamo (via ADAC)",
    confirmation: "20237222/01",
    vehicle: "Ford Escape AWD (oder ähnlich)",
    transmission: "Automatik",
    pickupDate: "2026-08-05",
    pickupTime: "10:00",
    pickupLocation: "Québec Airport (YQB)",
    pickupAddress: "505 Rue Principale, G2G 2T9 Québec",
    pickupPhone: "+1 418 877-0132",
    returnDate: "2026-08-17",
    returnTime: "13:00",
    returnLocation: "Halifax Airport (YHZ)",
    returnAddress: "747 Bell Boulevard, B2T 1K2 Enfield NS",
    returnPhone: "+1 902 873-3159",
    included: ["Vollkasko ohne SB (SLDW)", "Haftpflicht", "Zusatzhaftpflicht 1 Mio CAD", "1 Zusatzfahrer", "Unbegrenzte Kilometer", "Volltankprinzip"],
    document: "docs/mietwagen-adac.pdf",
  },

  accommodations: [
    {
      id: "montreal",
      name: "Novotel Montréal Centre",
      city: "Montréal, QC",
      lat: 45.502, lon: -73.567,
      address: "1180 Rue de la Montagne, H3G 1Z1 Montréal",
      phone: "+1 514 861-6000",
      checkIn:  "01.08.2026 ab 15:00",
      checkOut: "03.08.2026 bis 12:00",
      nights: 2,
      booking: "QFHSHLXW",
      mapsUrl: "https://maps.google.com/?q=Novotel+Montreal+Centre+1180+Rue+de+la+Montagne",
      document: "docs/hotel-montreal.pdf",
      color: "#2d6a9f",
    },
    {
      id: "quebec",
      name: "Delta Hotels Québec",
      city: "Québec, QC",
      lat: 46.814, lon: -71.208,
      address: "690 Boulevard René-Lévesque Est, G1R 5A8 Québec",
      phone: "+1 418 647-1717",
      checkIn:  "03.08.2026 ab 15:00",
      checkOut: "05.08.2026 bis 12:00",
      nights: 2,
      booking: "6347.265.983",
      pin: "9099",
      mapsUrl: "https://maps.google.com/?q=Delta+Hotels+Quebec+690+Boulevard+René-Lévesque",
      document: "docs/hotel-quebec.pdf",
      color: "#1a5276",
    },
    {
      id: "woodstock",
      name: "Best Western Plus Woodstock",
      city: "Woodstock, NB",
      lat: 46.151, lon: -67.573,
      address: "123 Gallop Court, E7M 3P7 Woodstock",
      phone: "+1 506 328-2378",
      checkIn:  "05.08.2026 ab 15:00",
      checkOut: "06.08.2026 bis 11:00",
      nights: 1,
      booking: "6860.144.068",
      pin: "3997",
      mapsUrl: "https://maps.google.com/?q=Best+Western+Plus+Woodstock+123+Gallop+Court",
      document: "docs/hotel-woodstock.pdf",
      color: "#1e8449",
    },
    {
      id: "pinecone",
      name: "Pinecone Motel",
      city: "Sussex, NB",
      lat: 45.723, lon: -65.510,
      address: "12808 Hwy 114, E4G 2Y8 Sussex",
      phone: "+1 506 433-3958",
      checkIn:  "06.08.2026 15:00–23:00",
      checkOut: "07.08.2026 bis 11:00",
      nights: 1,
      booking: "6752.466.015",
      pin: "9460",
      mapsUrl: "https://maps.google.com/?q=Pinecone+Motel+12808+Hwy+114+Sussex+NB",
      document: "docs/hotel-pinecone.pdf",
      color: "#6e2f1a",
    },
    {
      id: "cornwall",
      name: "Chez Nous",
      city: "Cornwall, PEI",
      lat: 46.238, lon: -63.215,
      address: "203 Ferry Road, COA 1H4 Cornwall",
      phone: "+1 647 880-3052",
      checkIn:  "07.08.2026 15:00–23:00",
      checkOut: "09.08.2026 07:00–11:00",
      nights: 2,
      booking: "5178.034.005",
      pin: "0625",
      mapsUrl: "https://maps.google.com/?q=203+Ferry+Road+Cornwall+PEI",
      document: "docs/hotel-cornwall.pdf",
      color: "#7d6608",
    },
    {
      id: "baddeck",
      name: "Trailsman Lodge",
      city: "Baddeck, NS",
      lat: 46.100, lon: -60.743,
      address: "10003 Hwy 105, B0E 1B0 Baddeck",
      phone: "+1 902 919-5780",
      checkIn:  "09.08.2026 16:00–23:00",
      checkOut: "12.08.2026 bis 11:00",
      nights: 3,
      booking: "5257.629.256",
      pin: "5210",
      note: "Zimmer mit Seeblick",
      mapsUrl: "https://maps.google.com/?q=Trailsman+Lodge+10003+Hwy+105+Baddeck",
      document: "docs/hotel-baddeck.pdf",
      color: "#1a3a5c",
    },
    {
      id: "halifax",
      name: "Chateau Bedford",
      city: "Halifax, NS",
      lat: 44.649, lon: -63.575,
      address: "133 Kearney Lake Road, B3M 4P3 Halifax",
      phone: "+1 902 445-1100",
      checkIn:  "12.08.2026 ab 15:00",
      checkOut: "17.08.2026 bis 11:00",
      nights: 5,
      booking: "6860.119.179",
      pin: "2249",
      mapsUrl: "https://maps.google.com/?q=Chateau+Bedford+133+Kearney+Lake+Road+Halifax",
      document: "docs/hotel-halifax.pdf",
      color: "#512e5f",
    },
  ],

  documents: [
    { id: "flug",      label: "Flüge (AUA/Air Canada)",  icon: "✈️", file: "docs/flug-wien-montreal.pdf" },
    { id: "auto",      label: "Mietwagen (ADAC/Alamo)",  icon: "🚗", file: "docs/mietwagen-adac.pdf" },
    { id: "montreal",  label: "Hotel Montréal",           icon: "🏨", file: "docs/hotel-montreal.pdf" },
    { id: "quebec",    label: "Hotel Québec",             icon: "🏨", file: "docs/hotel-quebec.pdf" },
    { id: "woodstock", label: "Hotel Woodstock",          icon: "🏨", file: "docs/hotel-woodstock.pdf" },
    { id: "pinecone",  label: "Pinecone Motel Sussex",   icon: "🏠", file: "docs/hotel-pinecone.pdf" },
    { id: "cornwall",  label: "Chez Nous Cornwall PEI",  icon: "🏡", file: "docs/hotel-cornwall.pdf" },
    { id: "baddeck",   label: "Trailsman Lodge Baddeck", icon: "🏕️", file: "docs/hotel-baddeck.pdf" },
    { id: "halifax",   label: "Hotel Halifax",            icon: "🏨", file: "docs/hotel-halifax.pdf" },
    { id: "eta-robert", label: "eTA Robert Preinfalk",   icon: "🛂", file: "docs/eta-robert.pdf" },
    { id: "eta-edith",  label: "eTA Edith Preinfalk",    icon: "🛂", file: "docs/eta-edith.pdf" },
    { id: "eta-pia",    label: "eTA Pia Preinfalk",      icon: "🛂", file: "docs/eta-pia.pdf" },
    { id: "pass-robert", label: "Reisepass Robert",              icon: "🪪", file: "docs/pass-robert.jpg" },
    { id: "pass-edith",  label: "Reisepass Edith",               icon: "🪪", file: "docs/pass-edith.jpg" },
    { id: "pass-pia",    label: "Reisepass Pia",                 icon: "🪪", file: "docs/pass-pia.jpg" },
    { id: "zug-robert",  label: "Zugticket Robert (VIA 24)",     icon: "🚆", file: "docs/zug-montreal-quebec-robert.pdf" },
    { id: "zug-edith",   label: "Zugticket Edith (VIA 24)",      icon: "🚆", file: "docs/zug-montreal-quebec-edith.pdf" },
    { id: "zug-pia",     label: "Zugticket Pia (VIA 24)",        icon: "🚆", file: "docs/zug-montreal-quebec-pia.pdf" },
  ],

  days: [
    {
      date: "2026-08-01", day: 1,
      title: "Abflug Wien → Montréal",
      location: "Montréal, QC",
      type: "flight",
      description: "Flug OS 55 ab Wien (11:00), Ankunft Montréal (13:50 Ortszeit). Check-in Novotel ab 15:00. Erster Abend in Montréal!",
      accommodation: "montreal",
      highlights: [],
    },
    {
      date: "2026-08-02", day: 2,
      title: "Montréal erkunden",
      location: "Montréal, QC",
      type: "explore",
      description: "Freier Tag in Montréal. Old Montréal, Basilique Notre-Dame, Plateau-Mont-Royal.",
      accommodation: "montreal",
      highlights: [
        { name: "Vieux-Montréal", mapsUrl: "https://maps.google.com/?q=Vieux-Montreal" },
        { name: "Basilique Notre-Dame", mapsUrl: "https://maps.google.com/?q=Notre-Dame+Basilica+Montreal" },
        { name: "Marché Jean-Talon", mapsUrl: "https://maps.google.com/?q=Marche+Jean-Talon+Montreal" },
      ],
    },
    {
      date: "2026-08-03", day: 3,
      title: "Montréal → Québec City",
      location: "Québec, QC",
      type: "train",
      description: "Check-out Novotel bis 12:00. Zug VIA 24 ab Montréal (12:45) → Québec (16:12). Wagen 4, Sitze 14A/14B/14C. Buchung: JW4PCM. Check-in Delta Hotels ab 15:00.",
      accommodation: "quebec",
      tickets: [
        { label: "Robert — Sitz 14B", file: "docs/zug-montreal-quebec-robert.pdf" },
        { label: "Edith — Sitz 14A",  file: "docs/zug-montreal-quebec-edith.pdf" },
        { label: "Pia — Sitz 14C",    file: "docs/zug-montreal-quebec-pia.pdf" },
      ],
      highlights: [
        { name: "Gare Centrale Montréal", mapsUrl: "https://maps.google.com/?q=Gare+Centrale+Montreal" },
        { name: "Vieux-Québec (UNESCO)", mapsUrl: "https://maps.google.com/?q=Old+Quebec+City" },
      ],
    },
    {
      date: "2026-08-04", day: 4,
      title: "Québec City",
      location: "Québec, QC",
      type: "explore",
      description: "Ganzer Tag in Québec City. Château Frontenac, Plaines d'Abraham, Chute Montmorency.",
      accommodation: "quebec",
      highlights: [
        { name: "Château Frontenac", mapsUrl: "https://maps.google.com/?q=Chateau+Frontenac+Quebec" },
        { name: "Chute Montmorency", mapsUrl: "https://maps.google.com/?q=Montmorency+Falls+Quebec" },
        { name: "Plaines d'Abraham", mapsUrl: "https://maps.google.com/?q=Plains+of+Abraham+Quebec" },
      ],
    },
    {
      date: "2026-08-05", day: 5,
      title: "Québec → Woodstock NB",
      location: "Woodstock, NB",
      type: "drive",
      description: "Check-out bis 12:00. Mietwagen-Abholung Québec Airport (YQB) um 10:00. Fahrt nach Woodstock (~4,5 Std.).",
      accommodation: "woodstock",
      highlights: [
        { name: "Alamo Quebec Airport", mapsUrl: "https://maps.google.com/?q=505+Rue+Principale+Quebec+YQB" },
      ],
    },
    {
      date: "2026-08-06", day: 6,
      title: "Woodstock → Sussex NB",
      location: "Sussex, NB",
      type: "drive",
      description: "Check-out bis 11:00. Fahrt nach Sussex (~1,5 Std.). Check-in Pinecone Motel.",
      accommodation: "pinecone",
      highlights: [
        { name: "Fundy Trail Parkway", mapsUrl: "https://maps.google.com/?q=Fundy+Trail+Parkway" },
      ],
    },
    {
      date: "2026-08-07", day: 7,
      title: "Sussex → Fähre → Cornwall PEI",
      location: "Cornwall, PEI",
      type: "ferry",
      description: "Check-out bis 11:00. Fahrt zur Confederation Bridge (~1 Std.). Überfahrt nach Prince Edward Island. Check-in Chez Nous.",
      accommodation: "cornwall",
      highlights: [
        { name: "Confederation Bridge", mapsUrl: "https://maps.google.com/?q=Confederation+Bridge+PEI" },
        { name: "Cavendish Beach", mapsUrl: "https://maps.google.com/?q=Cavendish+Beach+PEI" },
      ],
    },
    {
      date: "2026-08-08", day: 8,
      title: "Prince Edward Island",
      location: "Cornwall, PEI",
      type: "explore",
      description: "Ganzer Tag auf PEI. Rote Klippen, Cavendish, Green Gables (Anne of Green Gables).",
      accommodation: "cornwall",
      highlights: [
        { name: "Green Gables Heritage Place", mapsUrl: "https://maps.google.com/?q=Green+Gables+Heritage+Place+PEI" },
        { name: "Brackley Beach", mapsUrl: "https://maps.google.com/?q=Brackley+Beach+PEI" },
      ],
    },
    {
      date: "2026-08-09", day: 9,
      title: "Cornwall → Baddeck NS",
      location: "Baddeck, NS",
      type: "drive",
      description: "Frühzeitiger Check-out (07:00–11:00). Fähre zurück oder Causeway. Fahrt nach Baddeck (~3,5 Std.). Check-in Trailsman Lodge ab 16:00.",
      accommodation: "baddeck",
      highlights: [
        { name: "Canso Causeway", mapsUrl: "https://maps.google.com/?q=Canso+Causeway+Nova+Scotia" },
      ],
    },
    {
      date: "2026-08-10", day: 10,
      title: "Cape Breton — Cabot Trail Nord",
      location: "Baddeck, NS",
      type: "explore",
      description: "Cabot Trail Rundfahrt, nördlicher Teil. Cape Breton Highlands National Park. Atemberaubende Küstenlandschaft.",
      accommodation: "baddeck",
      highlights: [
        { name: "Cape Breton Highlands NP", mapsUrl: "https://maps.google.com/?q=Cape+Breton+Highlands+National+Park" },
        { name: "Pleasant Bay", mapsUrl: "https://maps.google.com/?q=Pleasant+Bay+Nova+Scotia" },
      ],
    },
    {
      date: "2026-08-11", day: 11,
      title: "Cape Breton — Cabot Trail Süd",
      location: "Baddeck, NS",
      type: "explore",
      description: "Cabot Trail, südlicher Teil. Alexander Graham Bell Museum in Baddeck. Entspannen am Bras d'Or Lake.",
      accommodation: "baddeck",
      highlights: [
        { name: "Alexander Graham Bell Museum", mapsUrl: "https://maps.google.com/?q=Alexander+Graham+Bell+Museum+Baddeck" },
        { name: "Bras d'Or Lake", mapsUrl: "https://maps.google.com/?q=Bras+d'Or+Lake+Nova+Scotia" },
      ],
    },
    {
      date: "2026-08-12", day: 12,
      title: "Baddeck → Halifax",
      location: "Halifax, NS",
      type: "drive",
      description: "Check-out bis 11:00. Fahrt nach Halifax (~3 Std.). Check-in Chateau Bedford ab 15:00.",
      accommodation: "halifax",
      highlights: [
        { name: "Peggy's Cove (auf dem Weg)", mapsUrl: "https://maps.google.com/?q=Peggy's+Cove+Nova+Scotia" },
      ],
    },
    {
      date: "2026-08-13", day: 13,
      title: "Halifax erkunden",
      location: "Halifax, NS",
      type: "explore",
      description: "Halifax Waterfront, Citadel Hill, Lunenburg Tagesausflug möglich.",
      accommodation: "halifax",
      highlights: [
        { name: "Halifax Waterfront", mapsUrl: "https://maps.google.com/?q=Halifax+Waterfront+Boardwalk" },
        { name: "Citadel Hill", mapsUrl: "https://maps.google.com/?q=Halifax+Citadel+National+Historic+Site" },
      ],
    },
    {
      date: "2026-08-14", day: 14,
      title: "Lunenburg & Mahone Bay",
      location: "Halifax, NS",
      type: "explore",
      description: "Tagesausflug nach Lunenburg (UNESCO) und Mahone Bay. Bunte Holzhäuser, historische Schiffswerft.",
      accommodation: "halifax",
      highlights: [
        { name: "Lunenburg (UNESCO)", mapsUrl: "https://maps.google.com/?q=Lunenburg+Nova+Scotia" },
        { name: "Mahone Bay", mapsUrl: "https://maps.google.com/?q=Mahone+Bay+Nova+Scotia" },
      ],
    },
    {
      date: "2026-08-15", day: 15,
      title: "Halifax — freier Tag",
      location: "Halifax, NS",
      type: "explore",
      description: "Freier Tag. Farmers Market, Public Gardens, Museum of Natural History oder Strandtag.",
      accommodation: "halifax",
      highlights: [
        { name: "Halifax Seaport Farmers' Market", mapsUrl: "https://maps.google.com/?q=Halifax+Seaport+Farmers+Market" },
        { name: "Halifax Public Gardens", mapsUrl: "https://maps.google.com/?q=Halifax+Public+Gardens" },
      ],
    },
    {
      date: "2026-08-16", day: 16,
      title: "Halifax — letzter Abend",
      location: "Halifax, NS",
      type: "explore",
      description: "Letzter voller Tag in Kanada. Abendessen am Waterfront. Koffer packen.",
      accommodation: "halifax",
      highlights: [
        { name: "Historic Properties", mapsUrl: "https://maps.google.com/?q=Historic+Properties+Halifax" },
      ],
    },
    {
      date: "2026-08-17", day: 17,
      title: "Rückflug Halifax → Wien",
      location: "Halifax, NS → Wien",
      type: "flight",
      description: "Check-out bis 11:00. Mietwagen-Rückgabe Halifax Airport 13:00. Flug LH 6557 um 14:05. Stopp Toronto.",
      accommodation: null,
      highlights: [],
    },
    {
      date: "2026-08-18", day: 18,
      title: "Ankunft Wien",
      location: "Wien, Österreich",
      type: "arrive",
      description: "Ankunft Wien 08:20. Willkommen zu Hause! Schöne Erinnerungen im Gepäck.",
      accommodation: null,
      highlights: [],
    },
  ],
};
